### ISSUE TITLE
request the finished pt file for the great result

### ISSUE THREAD

**Issue by jdjkim** [titus-leistner/epi-shift#1]
hi, dear author. Thanks for your excellent work and the great code in epi-shift . But, can you provide the finished pt file for the great results?  Our group also have some works which want to cite your great work. If it is not  convenient  in github, you can send it to my email: jdj18@mails.tsinghua.edu.cn   . thank you again

**Comment by titus-leistner** [comment]
Hi,
I added the parameter file "params.pt".

All the best
Titus
