### ISSUE TITLE
request the new unet network

### ISSUE THREAD

**Issue by jdjkim** [titus-leistner/epi-shift#2]
hi, it is so nice that you can provide the pt file, however, I find the unet model in this github can not fed with  the parameters.pt file, and the famous unet model from https://github.com/milesial/Pytorch-UNet can also not fit with the parameters.pt file. It seems that this parameters.pt file is trained in another unet model ,could you updata the content in github which can directly get the great results? Thanks!

**Comment by titus-leistner** [comment]
Hi, sorry, I uploaded the wrong version. You can find the right parameter file here:
https://heibox.uni-heidelberg.de/f/9462fa8a9d7a4b2aa513/?dl=1

Please also git pull as I have updated some default commandline flags.

Best
Titus
